apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels: { app: nginx-demo }
  template:
    metadata: { labels: { app: nginx-demo } }
    spec:
      containers:
      - name: nginx
        image: teerati/nginx-demo:latest
        imagePullPolicy: Always
        ports: [{ containerPort: 80 }]
        readinessProbe: { httpGet: { path: "/", port: 80 }, initialDelaySeconds: 3, periodSeconds: 5 }
        livenessProbe:  { httpGet: { path: "/", port: 80 }, initialDelaySeconds: 10, periodSeconds: 10 }
